# Generated by Django 5.2.17 on 2026-08-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passportuser',
            name='phone_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passportuser',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device', models.CharField(blank=True, default='', max_length=64)),
                ('device_type', models.CharField(choices=[('desktop', '桌面'), ('mobile', '手机'), ('tablet', '平板'), ('other', '其他')], default='other', max_length=16)),
                ('os', models.CharField(blank=True, default='', max_length=64)),
                ('browser', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_session',
                'ordering': ('-last_active_at',),
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('device_type', models.CharField(choices=[('desktop', '桌面'), ('mobile', '手机'), ('tablet', '平板'), ('other', '其他')], default='other', max_length=16)),
                ('os', models.CharField(blank=True, default='', max_length=64)),
                ('browser', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('trusted', models.BooleanField(default=False)),
                ('first_trusted_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_trusted_device',
                'ordering': ('-last_active_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_login_event',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='passport_lo_user_id_05853e_idx')],
            },
        ),
    ]
