# Generated by Django 5.2.17 on 2026-08-06 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_passportuser_bio_passportuser_phone_enc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportuser',
            name='totp_secret_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passportuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_backup_code',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['user', 'code_hash'], name='passport_ba_user_id_dca664_idx')],
            },
        ),
    ]
