# Generated by Django 5.2.17 on 2026-08-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0004_passkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportuser',
            name='totp_secret_enc',
        ),
        migrations.RemoveField(
            model_name='passportuser',
            name='two_factor_enabled',
        ),
        migrations.DeleteModel(
            name='BackupCode',
        ),
    ]
