# Generated by Django 5.2.17 on 2026-08-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0005_remove_passportuser_totp_secret_enc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_id', models.CharField(db_index=True, max_length=36)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'passport_account_deletion',
                'ordering': ('-deleted_at',),
            },
        ),
    ]
