# Generated by Django 5.2.17 on 2026-08-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0006_accountdeletion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passkey',
        ),
    ]
