# Generated by Django 6.0.7 on 2026-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('github', 'GitHub')], max_length=20, verbose_name='登录平台')),
                ('provider_user_id', models.CharField(max_length=128, verbose_name='第三方用户ID')),
                ('provider_username', models.CharField(blank=True, default='', max_length=100, verbose_name='第三方用户名')),
                ('access_token', models.CharField(blank=True, default='', max_length=512, verbose_name='访问令牌(加密)')),
                ('refresh_token', models.CharField(blank=True, default='', max_length=512, verbose_name='刷新令牌(加密)')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='令牌过期时间')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
            ],
            options={
                'verbose_name': '第三方账号绑定',
                'verbose_name_plural': '第三方账号绑定',
                'db_table': 'eacm_oauth_account',
            },
        ),
    ]
