# Generated by Django 6.0.7 on 2026-07-19 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthaccount',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
